### ISSUE TITLE
Pytest fails because OCC is missing

### ISSUE THREAD

**Issue by Zohra-D** [feelpp/BIM2Modelica#12]
@prudhomm, the pytests are not running since we moved to Ubuntu-22.04. Is Python OCC installed ?

**Comment by prudhomm** [comment]
We could install python-occ  or have a docker image with python-occ

**Comment by Zohra-D** [comment]
> We could install python-occ or have a docker image with python-occ

What about using Ktirio docker image ?

**Comment by prudhomm** [comment]
You can certainly use it. However it is a private image for a public repo

**Comment by Zohra-D** [comment]
@prudhomm this is not yet solved. We will not be able to merge the new changes.
