### ISSUE TITLE
Add github actions support

### ISSUE THREAD

**Issue by prudhomm** [feelpp/BIM2Modelica#3]

**Comment by prudhomm** [comment]
@FABallemand @Zohra-D can we set this up with what you have done so far?

**Comment by Zohra-D** [comment]
@prudhomm what do you mean by actions support ?

**Comment by prudhomm** [comment]
Github actions for eg continuous Integration

**Comment by prudhomm** [comment]
It means adding pipeline workflows to compile, run and test
